apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prow
  name: plugins
data:
  plugins.yaml: |
    plugins:
      gitpod-io/gitbot:
        plugins:
        - config-updater
      gitpod-io/gitpod-test-repo:
        plugins:
        - approve
        - assign
        - blunderbuss
        - cat
        - dog
        - goose
        - help
        - heart
        - hold
        - label
        - lgtm
        - size
        - verify-owners
        - wip
        - yuks

    external_plugins:
      "gitpod-io/gitpod-test-repo":
      - name: groundwork
        endpoint: http://groundwork.prow.svc.cluster.local:8787
        events:
        - issue_comment
      - name: projectmanager
        endpoint: http://projectmanager.prow.svc.cluster.local:8787
        events:
        - issues