apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prow
  name: plugins
data:
  plugins.yaml: |
    plugins:
      gitpod-io/gitbot:
        plugins:
        - config-updater
      gitpod-io/gitpod-test-repo:
        plugins:
        - approve
        - assign
        - blunderbuss
        - cat
        - dog
        - goose
        - help
        - heart
        - hold
        - label
        - lgtm
        - size
        - verify-owners
        - wip
        - yuks