# This file contains Kubernetes YAML files for the most important prow
# components. Don't edit resources in this file. Instead, pull them out into
# their own files.
---
apiVersion: v1
kind: Namespace
metadata:
  name: prow
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prow
  name: config
data:
  config.yaml: |
    prowjob_namespace: prow
    pod_namespace: test-pods

    in_repo_config:
      enabled:
        "*": true

    deck:
      branding:
        header_color: "#DADADA"
        logo: "/static/extensions/branding/logo.png"
      spyglass:
        lenses:
        - lens:
            name: metadata
          required_files:
          - started.json|finished.json
        - lens:
            config:
            name: buildlog
          required_files:
          - build-log.txt
        - lens:
            name: podinfo
          required_files:
          - podinfo.json

    plank:
      job_url_prefix_config:
        "*": https://prow.gitpod-dev.com/view/
      report_templates:
        '*': >-
            [Full PR test history](https://prow.gitpod-dev.com/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
            [Your PR dashboard](https://prow.gitpod-dev.com/pr?query=is:pr+state:open+author:{{with
            index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
      default_decoration_configs:
        "*":
          gcs_configuration:
            bucket: gs://gitpod-prow-artifacts
            path_strategy: explicit
          gcs_credentials_secret: gcs-credentials
          utility_images:
            clonerefs: gcr.io/k8s-prow/clonerefs:v20210707-32dc49e04b
            entrypoint: gcr.io/k8s-prow/entrypoint:v20210707-32dc49e04b
            initupload: gcr.io/k8s-prow/initupload:v20210707-32dc49e04b
            sidecar: gcr.io/k8s-prow/sidecar:v20210707-32dc49e04b

    tide:
      queries:
      - labels:
        - lgtm
        - approved
        missingLabels:
        - needs-rebase
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - do-not-merge/invalid-owners-file
        repos:
        - gitpod-io/gitpod-test-repo

    decorate_all_jobs: true
    # periodics:
    # - interval: 1m
    #   agent: kubernetes
    #   name: echo-test
    #   spec:
    #     containers:
    #     - image: alpine
    #       command: ["/bin/date"]
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: prowjobs.prow.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/test-infra/pull/8669"
spec:
  group: prow.k8s.io
  names:
    kind: ProwJob
    singular: prowjob
    plural: prowjobs
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              max_concurrency:
                type: integer
                minimum: 0
              type:
                type: string
                enum:
                - "presubmit"
                - "postsubmit"
                - "periodic"
                - "batch"
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              state:
                type: string
                enum:
                - "triggered"
                - "pending"
                - "success"
                - "failure"
                - "aborted"
                - "error"
            anyOf:
            - not:
                properties:
                  state:
                    enum:
                    - "success"
                    - "failure"
                    - "error"
            - required:
              - completionTime
    additionalPrinterColumns:
    - name: Job
      type: string
      description: The name of the job being run.
      jsonPath: .spec.job
    - name: BuildId
      type: string
      description: The ID of the job being run.
      jsonPath: .status.build_id
    - name: Type
      type: string
      description: The type of job being run.
      jsonPath: .spec.type
    - name: Org
      type: string
      description: The org for which the job is running.
      jsonPath: .spec.refs.org
    - name: Repo
      type: string
      description: The repo for which the job is running.
      jsonPath: .spec.refs.repo
    - name: Pulls
      type: string
      description: The pulls for which the job is running.
      jsonPath: ".spec.refs.pulls[*].number"
    - name: StartTime
      type: date
      description: When the job started running.
      jsonPath: .status.startTime
    - name: CompletionTime
      type: date
      description: When the job finished running.
      jsonPath: .status.completionTime
    - name: State
      description: The state of the job.
      type: string
      jsonPath: .status.state
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: prow
  name: prow
  annotations:
    # Change this to your issuer when using cert-manager. Does
    # nothing when not using cert-manager.
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  defaultBackend:
    # specify the default backend for `ingress-gce` (https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#default_backend)
    service:
      name: deck
      port:
        number: 80
  rules:
  - host: prow.gitpod-dev.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deck
            port:
              number: 80
      - path: /hook
        pathType: Prefix
        backend:
          service:
            name: hook
            port:
              number: 8888
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-pods